import DOMPurify from 'dompurify'
import { ARXIV_HTML } from '@/app/services'

export interface ArxivHtmlDocument {
  /** Sanitized body HTML, safe to inject. */
  html: string
  /** Section headings for the table of contents. */
  toc: Array<{ id: string; label: string; level: number }>
  abstract?: string
}

export class HtmlUnavailableError extends Error {
  constructor() {
    super('arXiv has no HTML version of this paper.')
    this.name = 'HtmlUnavailableError'
  }
}

/**
 * arXiv serves a friendly "no HTML available" NOTICE PAGE with HTTP 200 for
 * papers it hasn't converted (anything pre-2024, plus conversion failures).
 * Status codes therefore cannot be trusted here — the reliable signal is
 * whether the LaTeXML wrapper element is present. Verified against
 * arxiv.org/html/1706.03762, which returns 200 with no paper body.
 */
const LATEXML_ROOT = '.ltx_page_main'

/**
 * Fetch and clean a paper's HTML.
 *
 * arXiv sends `Access-Control-Allow-Origin: *` on /html/, so this works
 * directly from the browser with no proxy — which is what lets the whole app
 * run without a backend.
 */
export async function fetchArxivHtml(
  id: string,
  signal?: AbortSignal
): Promise<ArxivHtmlDocument> {
  const response = await fetch(ARXIV_HTML(id), { signal })
  if (!response.ok) throw new HtmlUnavailableError()

  const raw = await response.text()
  // Resolve assets against the URL the document was actually served from —
  // see absolutizeUrls. `response.url` is empty on some synthetic responses,
  // so fall back to what we asked for.
  const documentUrl = response.url || ARXIV_HTML(id)
  const parsed = new DOMParser().parseFromString(raw, 'text/html')
  const root = parsed.querySelector(LATEXML_ROOT)
  if (!root) throw new HtmlUnavailableError()

  stripChrome(root)
  absolutizeUrls(root, documentUrl)

  const toc = buildToc(root)
  const abstract = root.querySelector('.ltx_abstract p')?.textContent?.trim()

  // MathML must survive sanitization — arXiv's HTML renders equations natively
  // with it, and stripping it would silently gut every formula in the paper.
  const html = DOMPurify.sanitize(root.innerHTML, {
    USE_PROFILES: { html: true, mathMl: true, svg: true },
    ADD_TAGS: ['math', 'semantics', 'annotation', 'annotation-xml'],
    ADD_ATTR: ['id', 'class', 'display', 'mathvariant', 'scriptlevel', 'href', 'alttext'],
    FORBID_TAGS: ['script', 'style', 'iframe', 'form', 'object', 'embed', 'link'],
    FORBID_ATTR: ['srcset', 'ping', 'formaction'],
  })

  return { html, toc, abstract }
}

/** Remove arXiv's site navigation, banners and footers from the paper body. */
function stripChrome(root: Element): void {
  const selectors = [
    'header',
    'footer',
    'nav',
    '.ltx_page_header',
    '.ltx_page_footer',
    '.ltx_pagination',
    '#arxiv-base-header',
    '.extra-services',
    '.bookmarks',
    'script',
    'style',
    'link',
    // LaTeXML's "Generated by LaTeXML / view the build logs" footer.
    '.ltx_page_logo',
    '.ltx_watermark',
    // arXiv's licence banner and the "arXiv:1706.03762v7 [cs.CL]" stamp. These
    // are injected by arXiv around the paper, not written by the authors.
    '#infobox',
    '.infobox',
    '#license-tr',
    '#watermark-tr',
    // The app renders title, authors and abstract in its own header, so the
    // paper's copies are duplicates. Matched at any depth: on back-converted
    // older papers these sit several levels down, which a child selector
    // (as the stylesheet previously used) silently missed.
    '.ltx_title_document',
    '.ltx_authors',
    '.ltx_abstract',
  ]
  root.querySelectorAll(selectors.join(',')).forEach((node) => node.remove())

  // Anything else in the paper's front matter (author permission notices and
  // the like) is left alone: it is content the authors wrote, and removing
  // paragraphs by guessing at their text would eventually delete something
  // real.

  // arXiv's own logos and UI icons are served from /static/ and are not part
  // of the paper; figures from the paper live under the paper's own path.
  root.querySelectorAll('img[src^="/static/"]').forEach((node) => node.remove())
}

/**
 * Rewrite the paper's relative URLs to absolute ones, since the markup is
 * being moved into a page on a different origin and path.
 *
 * Resolution is against the URL the document was *served* from, exactly as a
 * browser would do it. The previous version built the base by appending a
 * slash to the paper URL, which treats "/html/2608.07460" as a directory when
 * it is a document: a figure src of "2608.07460v1/fig.png" then resolved to
 * "/html/2608.07460/2608.07460v1/fig.png" — one level too deep, and a 404 for
 * every figure in every paper. Nothing failed loudly; the images were simply
 * missing, and the 404s looked like ordinary console noise.
 */
function absolutizeUrls(root: Element, documentUrl: string): void {
  const base = documentUrl

  root.querySelectorAll<HTMLImageElement>('img[src]').forEach((img) => {
    const src = img.getAttribute('src')
    if (!src || /^(https?:|data:)/i.test(src)) return
    img.setAttribute('src', new URL(src, base).href)
    img.setAttribute('loading', 'lazy')
    img.setAttribute('decoding', 'async')
  })

  root.querySelectorAll<HTMLAnchorElement>('a[href]').forEach((anchor) => {
    const href = anchor.getAttribute('href')
    if (!href) return

    if (href.startsWith('#')) {
      // Intra-paper links (citations, figure refs) are handled by the reader's
      // own click handler; mark them so it can intercept.
      anchor.setAttribute('data-internal', 'true')
      return
    }
    if (!/^(https?:|mailto:)/i.test(href)) {
      anchor.setAttribute('href', new URL(href, base).href)
    }
    anchor.setAttribute('target', '_blank')
    anchor.setAttribute('rel', 'noopener noreferrer')
  })
}

function buildToc(root: Element): ArxivHtmlDocument['toc'] {
  const entries: ArxivHtmlDocument['toc'] = []

  root.querySelectorAll('.ltx_title_section, .ltx_title_subsection').forEach((heading) => {
    // The id lives on the enclosing section, not the heading itself.
    const section = heading.closest('section, div')
    const id = section?.id
    const label = heading.textContent?.trim()
    if (!id || !label) return
    entries.push({
      id,
      label,
      level: heading.classList.contains('ltx_title_subsection') ? 2 : 1,
    })
  })

  return entries
}
