import type { PaperDetail, PaperSummary } from '@/types'

/** Postings are flat triplets: [docIdDelta, fieldMask, quantizedWeight]. */
export type PostingList = number[]
export type IndexShard = Record<string, PostingList>

export interface Manifest {
  schema: 1
  builtAt: string
  docCount: number
  docsPerChunk: number
  chunkCount: number
  prefixLength: number
  categories: string[]
  abstractCutoff: string
  newestPublished: string
  oldestPublished: string
  avgFieldLengths: { title: number; author: number; category: number; abstract: number }
  shards: string[]
  metaShards: string[]
  idShards: string[]
  stats: { termCount: number; postingCount: number }
}

/**
 * Shard key for an arXiv id. MUST match idShardKey() in
 * scripts/build-index.mjs or paper lookups silently 404.
 */
export function idShardKey(id: string): string {
  const modern = /^(\d{4})\./.exec(id)
  if (modern) return modern[1]
  return id.split(/[./]/)[0].toLowerCase().replace(/[^a-z0-9]/g, '_') || 'other'
}

/** Positional tuple written by scripts/build-index.mjs. */
type SummaryTuple = [
  id: string,
  title: string,
  authors: string[],
  categories: string[],
  published: string,
  updated: string | 0,
]

const GZIP_MAGIC = [0x1f, 0x8b]

/**
 * Fetch a `.json.gz` shard.
 *
 * GitHub Pages serves `.gz` files as opaque bytes without a `Content-Encoding`
 * header, so the browser does NOT transparently decompress them — we do it
 * here with DecompressionStream. But some hosts (and dev servers) *do* set
 * that header, in which case fetch already decompressed the body. Sniffing the
 * gzip magic bytes handles both without needing to know which host we're on.
 */
async function fetchShard<T>(url: string, signal?: AbortSignal): Promise<T> {
  const response = await fetch(url, { signal })
  if (!response.ok) throw new ShardMissingError(url, response.status)

  const buffer = await response.arrayBuffer()
  const bytes = new Uint8Array(buffer)
  const isGzipped = bytes[0] === GZIP_MAGIC[0] && bytes[1] === GZIP_MAGIC[1]

  const text = isGzipped
    ? await new Response(
        new Blob([buffer]).stream().pipeThrough(new DecompressionStream('gzip'))
      ).text()
    : new TextDecoder().decode(buffer)

  assertJsonPayload(text, url)
  return JSON.parse(text) as T
}

/**
 * A missing data file doesn't 404 here: the SPA fallback (404.html on Pages,
 * the dev server's history fallback locally) answers with index.html and a
 * 200. Parsing that as JSON produces `Unexpected token '<'`, which tells the
 * user nothing. Detect it and say what is actually wrong.
 */
function assertJsonPayload(text: string, url: string): void {
  const start = text.trimStart()[0]
  if (start === '{' || start === '[') return
  throw new IndexUnavailableError(url)
}

export class IndexUnavailableError extends Error {
  constructor(readonly url: string) {
    super(
      'The search index has not been built for this deployment. It is generated by CI — ' +
        'run `npm run harvest && npm run build:index` to create it locally.'
    )
    this.name = 'IndexUnavailableError'
  }
}

export class ShardMissingError extends Error {
  constructor(
    readonly url: string,
    readonly status: number
  ) {
    super(`Shard unavailable (${status}): ${url}`)
    this.name = 'ShardMissingError'
  }
}

/**
 * Loads and caches the static corpus.
 *
 * Everything is cached in memory for the session; the service worker caches it
 * across sessions, which is what makes search work offline. Concurrent
 * requests for the same shard share one fetch, so a multi-term query issued
 * twice in quick succession doesn't double-fetch.
 */
export class CorpusClient {
  private manifestPromise?: Promise<Manifest>
  private readonly shards = new Map<string, Promise<IndexShard | null>>()
  private readonly docChunks = new Map<number, Promise<PaperSummary[]>>()
  private readonly metaShards = new Map<string, Promise<Record<string, MetaEntry> | null>>()
  private readonly idShards = new Map<string, Promise<Record<string, number> | null>>()

  constructor(private readonly baseUrl: string) {}

  manifest(): Promise<Manifest> {
    if (!this.manifestPromise) {
      this.manifestPromise = fetch(`${this.baseUrl}manifest.json`).then(async (response) => {
        const url = `${this.baseUrl}manifest.json`
        if (!response.ok) throw new IndexUnavailableError(url)

        const text = await response.text()
        assertJsonPayload(text, url)
        return JSON.parse(text) as Manifest
      })
      // A failed manifest must not be cached forever; let the next call retry.
      this.manifestPromise.catch(() => {
        this.manifestPromise = undefined
      })
    }
    return this.manifestPromise
  }

  /** Returns null when the shard doesn't exist — i.e. no paper has that term. */
  async shard(key: string, signal?: AbortSignal): Promise<IndexShard | null> {
    let pending = this.shards.get(key)
    if (!pending) {
      pending = fetchShard<IndexShard>(`${this.baseUrl}index/${key}.json.gz`, signal).catch(
        (error) => {
          if (error instanceof ShardMissingError) return null
          this.shards.delete(key)
          throw error
        }
      )
      this.shards.set(key, pending)
    }
    return pending
  }

  async docChunk(chunk: number, signal?: AbortSignal): Promise<PaperSummary[]> {
    let pending = this.docChunks.get(chunk)
    if (!pending) {
      pending = fetchShard<SummaryTuple[]>(
        `${this.baseUrl}docs/${chunk}.json.gz`,
        signal
      ).then((rows) => rows.map(toSummary))
      pending.catch(() => this.docChunks.delete(chunk))
      this.docChunks.set(chunk, pending)
    }
    return pending
  }

  /**
   * Resolve doc ids to display records, fetching only the chunks involved.
   * Ids are grouped so a page of results costs one fetch per distinct chunk.
   */
  async resolve(docIds: number[], signal?: AbortSignal): Promise<Map<number, PaperSummary>> {
    const manifest = await this.manifest()
    const byChunk = new Map<number, number[]>()
    for (const docId of docIds) {
      const chunk = Math.floor(docId / manifest.docsPerChunk)
      const bucket = byChunk.get(chunk)
      if (bucket) bucket.push(docId)
      else byChunk.set(chunk, [docId])
    }

    const resolved = new Map<number, PaperSummary>()
    await Promise.all(
      [...byChunk.entries()].map(async ([chunk, ids]) => {
        const rows = await this.docChunk(chunk, signal)
        for (const docId of ids) {
          const row = rows[docId - chunk * manifest.docsPerChunk]
          if (row) resolved.set(docId, row)
        }
      })
    )
    return resolved
  }

  /** Abstract and extras for a paper, or null if outside the built corpus. */
  async detail(summary: PaperSummary, signal?: AbortSignal): Promise<PaperDetail> {
    const month = summary.published.slice(0, 7).replace('-', '')
    let pending = this.metaShards.get(month)
    if (!pending) {
      pending = fetchShard<Record<string, MetaEntry>>(
        `${this.baseUrl}meta/${month}.json.gz`,
        signal
      ).catch((error) => {
        if (error instanceof ShardMissingError) return null
        this.metaShards.delete(month)
        throw error
      })
      this.metaShards.set(month, pending)
    }

    const entry = (await pending)?.[summary.id]
    return {
      ...summary,
      abstract: entry?.a ?? '',
      comment: entry?.c,
      doi: entry?.d,
      journalRef: entry?.j,
    }
  }

  /**
   * Find a paper by its arXiv id. Returns null when the paper isn't in the
   * built corpus — an older paper, or one outside the configured categories.
   * Callers fall back to deriving metadata from arXiv directly, so any paper
   * on arXiv still opens.
   */
  async findById(id: string, signal?: AbortSignal): Promise<PaperSummary | null> {
    const bare = id.replace(/v\d+$/, '')
    const key = idShardKey(bare)

    let pending = this.idShards.get(key)
    if (!pending) {
      pending = fetchShard<Record<string, number>>(
        `${this.baseUrl}ids/${key}.json.gz`,
        signal
      ).catch((error) => {
        if (error instanceof ShardMissingError) return null
        this.idShards.delete(key)
        throw error
      })
      this.idShards.set(key, pending)
    }

    const docId = (await pending)?.[bare]
    if (docId === undefined) return null

    const resolved = await this.resolve([docId], signal)
    return resolved.get(docId) ?? null
  }

  async recent(signal?: AbortSignal): Promise<PaperSummary[]> {
    const rows = await fetchShard<SummaryTuple[]>(`${this.baseUrl}recent.json.gz`, signal)
    return rows.map(toSummary)
  }
}

interface MetaEntry {
  a: string
  c?: string
  d?: string
  j?: string
}

function toSummary(tuple: SummaryTuple): PaperSummary {
  const [id, title, authors, categories, published, updated] = tuple
  return {
    id,
    title,
    authors,
    categories,
    published,
    updated: updated === 0 ? undefined : updated,
  }
}

/** Decode a delta-encoded postings list into absolute doc ids. */
export function* decodePostings(
  postings: PostingList
): Generator<{ docId: number; mask: number; weight: number }> {
  let docId = 0
  for (let i = 0; i < postings.length; i += 3) {
    docId += postings[i]
    yield { docId, mask: postings[i + 1], weight: postings[i + 2] }
  }
}
